### ISSUE TITLE
Little bug: Click the Test app will cause process quit

### ISSUE THREAD

**Issue by ayamir** [Celve/Peninsula#1]
Respect for your awesome app! Currently it has some little bugs like this:

![image](https://github.com/user-attachments/assets/95ed0d87-b41f-4189-ab30-48a2da02e844)

The process will quit when click the Test icon.

BTW, this app should have a designed icon. (just my personal advice)

**Comment by Celve** [comment]
I’ve uploaded a new release for [Peninsula v0.0.1](https://github.com/Celve/Peninsula/releases/tag/v0.0.1), which includes a patch that I believe resolves this issue.

Additionally, I’ve updated the v0.0.1 tag to point to the patched commit. If you’re building the app yourself, please ensure you use the corrected commit to avoid any inconsistencies.

**Comment by Celve** [comment]
Besides, I will add an icon for it. I just forgot to do this. lol

**Comment by Celve** [comment]
I believe the newest patch has resolved it. Please reopen this issue if the problem still exists.
