### ISSUE TITLE
Does Peninsula work on without-notch screen?

### ISSUE THREAD

**Issue by willweimike** [Celve/Peninsula#11]
Hello! Thank you for your great work! Does Peninsula work on without-notch screen?

**Comment by Celve** [comment]
If you don’t enable auto-hide for your menu bar, Peninsula will appear centered on it. However, when auto-hide is enabled, it might obstruct your view like #2. It will be fixed in coming releases.

**Comment by willweimike** [comment]
Wow! It's pretty nice!
Thank you!
