### ISSUE TITLE
通知反馈

### ISSUE THREAD

**Issue by zenstoneWX** [Celve/Peninsula#15]
确实添加了微信，也打开了系统通知，但是在插件里没有通知提醒

**Comment by Celve** [comment]
请问是macOS14 or macOS15？微信的通知提醒是基于检测dock栏微信图标红点数字的变化来实现的，所以在设置中需要将微信的badge application icon打开。
路径：settings -> notifications -> wechat -> badge application icon
<img width="483" alt="image" src="https://github.com/user-attachments/assets/35f7cf97-afb2-4987-baed-11a1cc4b935d">

**Comment by Celve** [comment]
如果是macOS14的话也有可能有些相关的bug，我自用是macOS15

**Comment by zenstoneWX** [comment]
通知设置都按照要求打开了，系统是15.1.1
![截图1](https://github.com/user-attachments/assets/917b992d-2cde-4c02-8612-3418aa36667e)
![截图2](https://github.com/user-attachments/assets/486c12cc-5d71-4aa8-885d-11b94ad6f92a)
![截图3](https://github.com/user-attachments/assets/61b48487-f259-488a-8d48-46127f6af3ed)

**Comment by Celve** [comment]
我在中文系统中复现了，应该是系统语言的问题，之后会找时间修下

**Comment by Celve** [comment]
目测英文系统不会出现这个情况

**Comment by zenstoneWX** [comment]
好的 麻烦您了

**Comment by Celve** [comment]
看一下这个release？应该解决了：https://github.com/Celve/Peninsula/releases/tag/v0.0.6

**Comment by zenstoneWX** [comment]
感谢作者

**Comment by zenstoneWX** [comment]
这个版本显示恶意软件……

**Comment by Celve** [comment]
> 这个版本显示恶意软件……

我研究下...

**Comment by Celve** [comment]
我重新上传了一份：https://github.com/Celve/Peninsula/releases/tag/v0.0.6，麻烦看看这个可不可以？
关于malware的事情，我正在申请apple developer id，之后可以作notarization应该就不会用这个问题了。不过还在等apple developer id review

**Comment by zenstoneWX** [comment]
可以啦，感谢您
