### ISSUE TITLE
See all apps after start

### ISSUE THREAD

**Issue by warmup72** [Celve/Peninsula#20]
Unfortunately, you can't see all open programmes after starting the app. You first have to click on every single programme that is open again.
This is a little inconvenient, especially as it is not possible to ensure that Penunsula is started first after a restart

**Comment by Celve** [comment]
I can see all windows that are opened before starting Peninsula. I cannot reproduce this on my device.

**Comment by warmup72** [comment]
Works wir 0.0.6
