### ISSUE TITLE
0.0.2在外接屏上显示位置在屏幕中间^-^

### ISSUE THREAD

**Issue by pigxiang** [Celve/Peninsula#4]
![Uploading Snipaste_2024-12-06_09-47-46.jpg…]()

系统14.6.1
无头骑士，
外接4K显示器作为主屏，
显示的位置在屏幕中间~~~像小胡子

**Comment by Celve** [comment]
是在正中间嘛？应该是和macOS14相关的bug

**Comment by pigxiang** [comment]
差不多是屏幕往下点点， 55%的位置，更新了下截图

**Comment by Celve** [comment]
图片似乎有些问题；
然后你可以正常和notch交互对吧：即点击notch会有相关反应

**Comment by pigxiang** [comment]
> 图片似乎有些问题； 然后你可以正常和notch交互对吧：即点击notch会有相关反应

点击“刘海”位置（虽然外接屏没刘海），
有反应，和笔记本上一样~
![Snipaste_2024-12-06_09-53-40](https://github.com/user-attachments/assets/438b3d80-c55d-4d5b-826c-935d0d11ee8a)

**Comment by Celve** [comment]
想问一下设备是Mac mini嘛？

**Comment by pigxiang** [comment]
> 想问一下设备是Mac mini嘛？

macbook pro 16 2019 intel版，下半部，
自己没显示屏~~~
插外接屏用

**Comment by fa3eng** [comment]
+1，同样的问题，我外接了一个显示器，显示器和自带的屏幕都出现了这个问题

* MacBook Pro 16寸 M1Pro
* MacOS 版本 14.5

**Comment by Celve** [comment]
我目前是macOS15，我会尝试在macOS14的虚拟机上复现

**Comment by Celve** [comment]
成功在macOS14的虚拟机上复现了，预计两天内解决

**Comment by Celve** [comment]
Resolved in https://github.com/Celve/Peninsula/releases/tag/v0.0.3
我在虚拟机上解决了这个问题，如果依然存在请重新打开这个issue

**Comment by pigxiang** [comment]
> Resolved in https://github.com/Celve/Peninsula/releases/tag/v0.0.3 我在虚拟机上解决了这个问题，如果依然存在请重新打开这个issue

这效率忒快了呀~~~那台电脑在公司，周一去试试~
