### ISSUE TITLE
macOS 14.7  显示位置不对

### ISSUE THREAD

**Issue by VandeeFeng** [Celve/Peninsula#6]
鼠标移动到刘海区域有正常交互，就是位置不对.

体验上，很舒服。建议加上一个退出的说明.

![PixPin_2024-12-06_12-58-23](https://github.com/user-attachments/assets/7d1cdb42-6f91-4113-bd6d-a057e5d4cc58)

**Comment by Celve** [comment]
Duplicate #4，已经成功复现了，会在两天内解决，预计发布于v0.0.3

**Comment by VandeeFeng** [comment]
> Duplicate #4，已经成功复现了，会在两天内解决，预计发布于v0.0.3

很喜欢这个 app 的实现，挺方便的。

**Comment by Celve** [comment]
> > Duplicate #4，已经成功复现了，会在两天内解决，预计发布于v0.0.3
> 
> 很喜欢这个 app 的实现，挺方便的。

感谢，如果有什么好的建议欢迎提issue
